# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-11 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(upload_to='studio/'),
        ),
    ]
